from util import PROJECT_PATH,SEGMENTED

IMAGE_NUMBER = "1"  # 1, 2, 3, 4
FILE_EXTENSION = ".png"
DENOISED_FOLDER = "\\images\\denoised\\denoised_image" + IMAGE_NUMBER + "\\"

CHOSEN_FILTER = "nl_means" # bilateral, gaussian, median, tv, wavelet, fourier_butterworthLP, fourier_idealLP, fourier_gaussianLP
DEFAULT_IMAGE = PROJECT_PATH + "\\images\\default_image" +IMAGE_NUMBER + FILE_EXTENSION


GAUSSIAN_LOW = PROJECT_PATH + DENOISED_FOLDER + CHOSEN_FILTER + "_filter\\gaussian\\gaussian_low_" + CHOSEN_FILTER + FILE_EXTENSION
GAUSSIAN_MODERATE = PROJECT_PATH + DENOISED_FOLDER + CHOSEN_FILTER + "_filter\\gaussian\\gaussian_moderate_" + CHOSEN_FILTER + FILE_EXTENSION
GAUSSIAN_HIGH = PROJECT_PATH + DENOISED_FOLDER + CHOSEN_FILTER + "_filter\\gaussian\\gaussian_high_" + CHOSEN_FILTER + FILE_EXTENSION

LAPLACIAN_LOW = PROJECT_PATH + DENOISED_FOLDER + CHOSEN_FILTER + "_filter\\laplacian\\laplacian_low_" + CHOSEN_FILTER + FILE_EXTENSION
LAPLACIAN_MODERATE = PROJECT_PATH + DENOISED_FOLDER + CHOSEN_FILTER + "_filter\\laplacian\\laplacian_moderate_" + CHOSEN_FILTER + FILE_EXTENSION
LAPLACIAN_HIGH = PROJECT_PATH + DENOISED_FOLDER + CHOSEN_FILTER + "_filter\\laplacian\\laplacian_high_" + CHOSEN_FILTER + FILE_EXTENSION

POISSON_LOW = PROJECT_PATH + DENOISED_FOLDER + CHOSEN_FILTER + "_filter\\poisson\\poisson_low_" + CHOSEN_FILTER + FILE_EXTENSION
POISSON_MODERATE = PROJECT_PATH + DENOISED_FOLDER + CHOSEN_FILTER + "_filter\\poisson\\poisson_moderate_" + CHOSEN_FILTER + FILE_EXTENSION
POISSON_HIGH = PROJECT_PATH + DENOISED_FOLDER + CHOSEN_FILTER + "_filter\\poisson\\poisson_high_" + CHOSEN_FILTER + FILE_EXTENSION

SPECKLE_LOW = PROJECT_PATH + DENOISED_FOLDER + CHOSEN_FILTER + "_filter\\speckle\\speckle_low_" + CHOSEN_FILTER + FILE_EXTENSION
SPECKLE_MODERATE = PROJECT_PATH + DENOISED_FOLDER + CHOSEN_FILTER + "_filter\\speckle\\speckle_moderate_" + CHOSEN_FILTER + FILE_EXTENSION
SPECKLE_HIGH = PROJECT_PATH + DENOISED_FOLDER + CHOSEN_FILTER + "_filter\\speckle\\speckle_high_" + CHOSEN_FILTER + FILE_EXTENSION

UNIFORM_LOW = PROJECT_PATH + DENOISED_FOLDER + CHOSEN_FILTER + "_filter\\uniform\\uniform_low_" + CHOSEN_FILTER + FILE_EXTENSION
UNIFORM_MODERATE = PROJECT_PATH + DENOISED_FOLDER + CHOSEN_FILTER + "_filter\\uniform\\uniform_moderate_" + CHOSEN_FILTER + FILE_EXTENSION
UNIFORM_HIGH = PROJECT_PATH + DENOISED_FOLDER + CHOSEN_FILTER + "_filter\\uniform\\uniform_high_" + CHOSEN_FILTER + FILE_EXTENSION

PEPPER_LOW = PROJECT_PATH + DENOISED_FOLDER + CHOSEN_FILTER + "_filter\\pepper\\pepper_low_" + CHOSEN_FILTER + FILE_EXTENSION
PEPPER_MODERATE = PROJECT_PATH + DENOISED_FOLDER + CHOSEN_FILTER + "_filter\\pepper\\pepper_moderate_" + CHOSEN_FILTER + FILE_EXTENSION
PEPPER_HIGH = PROJECT_PATH + DENOISED_FOLDER + CHOSEN_FILTER + "_filter\\pepper\\pepper_high_" + CHOSEN_FILTER + FILE_EXTENSION

SALT_LOW = PROJECT_PATH + DENOISED_FOLDER + CHOSEN_FILTER + "_filter\\salt\\salt_low_" + CHOSEN_FILTER + FILE_EXTENSION
SALT_MODERATE = PROJECT_PATH + DENOISED_FOLDER + CHOSEN_FILTER + "_filter\\salt\\salt_moderate_" + CHOSEN_FILTER + FILE_EXTENSION
SALT_HIGH = PROJECT_PATH + DENOISED_FOLDER + CHOSEN_FILTER + "_filter\\salt\\salt_high_" + CHOSEN_FILTER + FILE_EXTENSION

SP_LOW = PROJECT_PATH + DENOISED_FOLDER + CHOSEN_FILTER + "_filter\\salt&pepper\\salt&pepper_low_" + CHOSEN_FILTER + FILE_EXTENSION
SP_MODERATE = PROJECT_PATH + DENOISED_FOLDER + CHOSEN_FILTER + "_filter\\salt&pepper\\salt&pepper_moderate_" + CHOSEN_FILTER + FILE_EXTENSION
SP_HIGH = PROJECT_PATH + DENOISED_FOLDER + CHOSEN_FILTER + "_filter\\salt&pepper\\salt&pepper_high_" + CHOSEN_FILTER + FILE_EXTENSION